<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository {
    
    public function orderBy( $order = 'title', $direction = 'ASC', $returnType = 'entity' ){
        $todos = $this->getEntityManager()
            ->createQuery( 'SELECT todo FROM AppBundle\Entity\Todo todo ORDER BY todo.' . $order . ' ' . $direction  );

        if( $returnType == 'array' ){
            return $todos->getArrayResult();
        }

        return $todos->getResult();
    }

}
